# ACS Data Analysis

* Add description of what the purpose of this notebook is
* Overview of the steps etc
*

### Setup

In [1]:
import pandas as pd
import geopandas as gpd
import numpy as np
import camelot
import calendar
import re
import matplotlib.pyplot as plt

## 1. ACSDP05 (demographic data) (ACS data 1/3)

In [2]:
ACS5 = pd.read_csv('../data/ACSDP05.csv')

ACS5.shape

(99, 237)

In [3]:
ACS5.head(30)

,Label (Grouping),"Alameda County, California!!Estimate","Alameda County, California!!Margin of Error","Alameda County, California!!Percent","Alameda County, California!!Percent Margin of Error","Alpine County, California!!Estimate","Alpine County, California!!Margin of Error","Alpine County, California!!Percent","Alpine County, California!!Percent Margin of Error","Amador County, California!!Estimate",...,"Yolo County, California!!Percent","Yolo County, California!!Percent Margin of Error","Yuba County, California!!Estimate","Yuba County, California!!Margin of Error","Yuba County, California!!Percent","Yuba County, California!!Percent Margin of Error",ZCTA5 99641!!Estimate,ZCTA5 99641!!Margin of Error,ZCTA5 99641!!Percent,ZCTA5 99641!!Percent Margin of Error
0,SEX AND AGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Total population,"1,651,949",*****,"1,651,949",(X),"1,695",±234,"1,695",(X),"41,029",...,"217,782",(X),"83,079",*****,"83,079",(X),766.0,±166,766,(X)
2,Male,"819,520",*****,49.6%,*****,885,±148,52.2%,±4.8,"22,409",...,48.7%,±0.1,"42,183",±211,50.8%,±0.3,356.0,±77,46.5%,±5.5
3,Female,"832,429",*****,50.4%,*****,810,±139,47.8%,±4.8,"18,620",...,51.3%,±0.1,"40,896",±211,49.2%,±0.3,410.0,±108,53.5%,±5.5
4,Sex ratio (males per 100 females),98.4,*****,(X),(X),109.3,±21.4,(X),(X),120.3,...,(X),(X),103.1,±1.0,(X),(X),86.8,±20.0,(X),(X)
5,Under 5 years,"88,228",*****,5.3%,*****,161,±85,9.5%,±4.6,"1,587",...,5.0%,±0.1,"6,099",±7,7.3%,±0.1,103.0,±39,13.4%,±3.6
6,5 to 9 years,"91,717","±1,746",5.6%,±0.1,83,±39,4.9%,±2.2,"1,712",...,5.7%,±0.3,"7,148",±612,8.6%,±0.7,112.0,±36,14.6%,±2.8
7,10 to 14 years,"94,521","±1,746",5.7%,±0.1,56,±30,3.3%,±1.8,"1,857",...,6.0%,±0.3,"6,015",±606,7.2%,±0.7,74.0,±34,9.7%,±3.5
8,15 to 19 years,"96,042",±147,5.8%,±0.1,115,±58,6.8%,±3.0,"1,776",...,9.7%,±0.1,"5,568",±148,6.7%,±0.2,58.0,±19,7.6%,±2.2
9,20 to 24 years,"91,539",±148,5.5%,±0.1,102,±73,6.0%,±4.2,"1,593",...,13.8%,±0.1,"5,311",±183,6.4%,±0.2,68.0,±26,8.9%,±3.1
10,25 to 34 years,"260,856",*****,15.8%,*****,171,±90,10.1%,±4.9,"4,522",...,13.4%,±0.1,"12,789",±276,15.4%,±0.3,74.0,±29,9.7%,±3.4
11,35 to 44 years,"259,960",*****,15.7%,*****,244,±98,14.4%,±5.4,"5,219",...,12.3%,±0.1,"11,653",±228,14.0%,±0.3,88.0,±31,11.5%,±2.9
12,45 to 54 years,"220,682",*****,13.4%,*****,114,±66,6.7%,±3.8,"5,008",...,10.6%,±0.1,"8,501",±239,10.2%,±0.3,37.0,±17,4.8%,±2.0
13,55 to 59 years,"105,447","±1,906",6.4%,±0.1,168,±96,9.9%,±5.3,"2,581",...,5.1%,±0.3,"4,249",±461,5.1%,±0.6,33.0,±14,4.3%,±1.8
14,60 to 64 years,"96,116","±1,905",5.8%,±0.1,112,±57,6.6%,±3.3,"4,011",...,5.2%,±0.3,"4,857",±455,5.8%,±0.5,28.0,±16,3.7%,±2.2
15,65 to 74 years,"146,260",*****,8.9%,*****,336,±82,19.8%,±4.6,"6,747",...,7.9%,±0.1,"6,912",±164,8.3%,±0.2,72.0,±35,9.4%,±3.9
16,75 to 84 years,"70,518","±1,156",4.3%,±0.1,22,±15,1.3%,±0.9,"3,212",...,3.7%,±0.2,"3,086",±258,3.7%,±0.3,15.0,±10,2.0%,±1.4
17,85 years and over,"30,063","±1,156",1.8%,±0.1,11,±15,0.6%,±0.8,"1,204",...,1.6%,±0.2,891,±235,1.1%,±0.3,4.0,±6,0.5%,±0.8
18,Median age (years),38.7,±0.2,(X),(X),41.1,±4.8,(X),(X),49.9,...,(X),(X),33.9,±0.3,(X),(X),23.4,±3.1,(X),(X)
19,Under 18 years,"331,035",*****,20.0%,*****,383,±104,22.6%,±4.8,"6,356",...,20.5%,*****,"22,640",±143,27.3%,±0.2,320.0,±96,41.8%,±6.0
20,16 years and over,"1,359,199",±728,82.3%,±0.1,"1,366",±202,80.6%,±4.9,"35,564",...,81.9%,±0.2,"62,578",±323,75.3%,±0.4,472.0,±97,61.6%,±6.1
21,18 years and over,"1,320,914",*****,80.0%,*****,"1,312",±191,77.4%,±4.8,"34,673",...,79.5%,*****,"60,439",±143,72.7%,±0.2,446.0,±91,58.2%,±6.0
22,21 years and over,"1,262,399","±1,010",76.4%,±0.1,"1,280",±180,75.5%,±4.9,"33,669",...,69.9%,±0.5,"57,204",±248,68.9%,±0.3,413.0,±88,53.9%,±6.0
23,62 years and over,"301,112","±1,806",18.2%,±0.1,465,±94,27.4%,±5.0,"13,651",...,16.1%,±0.2,"13,669",±400,16.5%,±0.5,110.0,±38,14.4%,±4.4
24,65 years and over,"246,841",*****,14.9%,*****,369,±83,21.8%,±4.6,"11,163",...,13.3%,±0.1,"10,889",±108,13.1%,±0.1,91.0,±36,11.9%,±4.0
25,18 years and over,"1,320,914",*****,"1,320,914",(X),"1,312",±191,"1,312",(X),"34,673",...,"173,144",(X),"60,439",±143,"60,439",(X),446.0,±91,446,(X)
26,Male,"649,970",*****,49.2%,*****,682,±129,52.0%,±5.4,"19,020",...,48.1%,±0.1,"30,757",±100,50.9%,±0.1,239.0,±55,53.6%,±6.7
27,Female,"670,944",*****,50.8%,*****,630,±111,48.0%,±5.4,"15,653",...,51.9%,±0.1,"29,682",±124,49.1%,±0.1,207.0,±54,46.4%,±6.7
28,Sex ratio (males per 100 females),96.9,*****,(X),(X),108.3,±24.1,(X),(X),121.5,...,(X),(X),103.6,±0.6,(X),(X),115.5,±33.4,(X),(X)
29,65 years and over,"246,841",*****,"246,841",(X),369,±83,369,(X),"11,163",...,"28,915",(X),"10,889",±108,"10,889",(X),91.0,±36,91,(X)

* Selecting just the percent and estimate columns

In [4]:
estimate_cols = [c for c in ACS5.columns if c.endswith('!!Estimate')]
percent_cols = [c for c in ACS5.columns if c.endswith('!!Percent')]

* Cleaning the county names

In [5]:
county_names = [c.split('!!')[0].strip() for c in percent_cols]

* Searching/selecting for median age row

In [6]:
median_idx = ACS5['Label (Grouping)'].astype(str).str.contains('Median age', na=False)

* Constructing final dataset by locating desired measures and renaming columns

In [7]:
ACS5_final = pd.DataFrame({
    'county': county_names,
    'median_age': ACS5.loc[median_idx, estimate_cols].iloc[0].values,
    'pct_white': ACS5.loc[71, percent_cols].values,
    'pct_black': ACS5.loc[72, percent_cols].values,
    'pct_native': ACS5.loc[73, percent_cols].values,
    'pct_asian': ACS5.loc[74, percent_cols].values,
    'pct_other': ACS5.loc[76, percent_cols].values,
    'pct_hispanic': ACS5.loc[79, percent_cols].values,
})

In [8]:
ACS5_final

,county,median_age,pct_white,pct_black,pct_native,pct_asian,pct_other,pct_hispanic
0,"Alameda County, California",38.7,41.8%,12.1%,2.1%,36.1%,19.1%,23.3%
1,"Alpine County, California",41.1,71.0%,0.0%,28.1%,0.5%,8.3%,14.7%
2,"Amador County, California",49.9,89.0%,3.7%,5.0%,3.6%,12.3%,15.5%
3,"Butte County, California",36.3,84.3%,3.1%,4.3%,7.1%,13.6%,19.5%
4,"Calaveras County, California",52.0,91.6%,1.6%,3.8%,3.2%,10.8%,13.9%
5,"Colusa County, California",35.7,70.6%,2.1%,3.2%,2.1%,42.1%,62.3%
6,"Contra Costa County, California",40.3,56.4%,10.8%,2.6%,22.4%,22.6%,27.3%
7,"Del Norte County, California",40.8,78.1%,3.9%,10.3%,4.8%,14.0%,19.6%
8,"El Dorado County, California",46.1,88.8%,1.7%,2.5%,7.5%,8.9%,14.2%
9,"Fresno County, California",33.2,61.6%,6.0%,3.1%,12.8%,38.1%,54.1%
10,"Glenn County, California",35.9,74.0%,1.0%,3.8%,3.4%,32.5%,44.1%
11,"Humboldt County, California",39.6,85.2%,3.2%,8.6%,5.2%,10.6%,13.8%
12,"Imperial County, California",33.0,55.6%,3.7%,2.7%,2.3%,62.7%,85.6%
13,"Inyo County, California",45.6,78.3%,1.3%,15.1%,2.8%,15.5%,23.8%
14,"Kern County, California",32.4,69.8%,6.7%,2.9%,6.5%,36.1%,55.7%
15,"Kings County, California",32.3,65.5%,7.9%,3.1%,5.1%,38.7%,57.5%
16,"Lake County, California",44.2,80.2%,3.7%,6.6%,2.5%,19.1%,23.8%
17,"Lassen County, California",37.8,82.7%,9.5%,5.1%,2.6%,13.7%,22.5%
18,"Los Angeles County, California",37.9,50.9%,9.4%,2.7%,17.2%,37.0%,48.3%
19,"Madera County, California",34.6,61.3%,4.1%,5.0%,3.5%,45.5%,60.4%
20,"Marin County, California",47.3,80.5%,3.6%,1.9%,9.0%,15.8%,19.0%
21,"Mariposa County, California",51.6,89.1%,2.4%,6.2%,2.5%,11.0%,13.7%
22,"Mendocino County, California",43.9,84.8%,1.7%,6.8%,3.1%,20.6%,26.9%
23,"Merced County, California",31.8,46.9%,4.4%,3.0%,8.8%,49.5%,62.7%
24,"Modoc County, California",49.0,89.6%,1.5%,6.3%,1.5%,10.0%,15.3%
25,"Mono County, California",40.3,89.6%,0.5%,6.8%,3.6%,16.1%,26.7%
26,"Monterey County, California",35.3,49.0%,3.4%,2.5%,7.7%,51.1%,61.0%
27,"Napa County, California",42.8,73.2%,3.4%,2.5%,10.5%,24.8%,35.9%
28,"Nevada County, California",50.3,94.5%,1.2%,2.6%,3.5%,7.7%,10.5%
29,"Orange County, California",39.1,60.4%,2.7%,2.0%,25.0%,25.0%,34.1%
30,"Placer County, California",42.4,84.0%,3.2%,2.4%,12.2%,11.1%,15.4%
31,"Plumas County, California",52.1,94.7%,3.1%,4.9%,1.1%,3.9%,10.0%
32,"Riverside County, California",36.7,59.5%,8.4%,3.1%,9.1%,39.1%,50.6%
33,"Sacramento County, California",37.2,58.8%,13.0%,3.1%,20.9%,17.4%,24.0%
34,"San Benito County, California",35.9,76.9%,1.9%,4.5%,6.7%,43.7%,61.7%
35,"San Bernardino County, California",34.4,56.4%,10.1%,3.0%,10.0%,39.5%,54.6%
36,"San Diego County, California",37.1,70.0%,6.6%,2.5%,15.6%,23.6%,34.3%
37,"San Francisco County, California",39.7,50.1%,6.8%,1.8%,39.1%,13.1%,15.9%
38,"San Joaquin County, California",35.2,55.1%,9.1%,6.1%,21.1%,30.5%,42.2%
39,"San Luis Obispo County, California",40.2,86.8%,2.5%,2.6%,5.9%,17.5%,24.5%
40,"San Mateo County, California",40.6,52.2%,3.3%,2.2%,34.4%,19.6%,24.9%
41,"Santa Barbara County, California",34.5,76.8%,2.9%,3.6%,7.4%,33.0%,47.6%
42,"Santa Clara County, California",37.9,45.5%,3.6%,1.9%,42.7%,19.7%,25.1%
43,"Santa Cruz County, California",39.6,75.8%,2.3%,3.0%,7.0%,26.3%,35.0%
44,"Shasta County, California",41.7,90.7%,2.4%,5.1%,5.0%,8.3%,11.3%
45,"Sierra County, California",56.0,93.7%,0.3%,2.6%,0.0%,6.7%,9.6%
46,"Siskiyou County, California",47.4,90.1%,2.7%,7.6%,3.2%,7.6%,13.1%
47,"Solano County, California",39.1,55.1%,16.4%,2.8%,20.4%,19.5%,29.0%
48,"Sonoma County, California",42.7,77.5%,2.9%,3.7%,6.6%,23.3%,29.4%
49,"Stanislaus County, California",34.8,73.3%,4.3%,3.3%,7.9%,35.6%,49.2%
50,"Sutter County, California",36.4,65.3%,3.7%,4.3%,20.0%,22.9%,32.4%
51,"Tehama County, California",40.1,84.4%,1.6%,5.0%,2.5%,22.7%,28.2%
52,"Trinity County, California",54.8,88.6%,1.1%,5.6%,2.9%,9.4%,5.9%
53,"Tulare County, California",31.9,63.3%,2.2%,3.3%,4.6%,48.4%,66.1%
54,"Tuolumne County, California",48.8,91.0%,2.3%,4.4%,2.9%,8.2%,13.2%
55,"Ventura County, California",39.4,78.7%,3.2%,3.3%,9.6%,26.6%,43.8%
56,"Yolo County, California",32.3,69.9%,4.3%,2.8%,18.7%,21.0%,33.2%
57,"Yuba County, California",33.9,76.1%,7.0%,5.7%,10.4%,18.6%,30.0%
58,ZCTA5 99641,23.4,1.4%,0.0%,99.6%,0.0%,0.4%,1.7%

#### Convert to numeric

In [17]:
ACS5_final['county'] = ACS5_final['county'].str.replace(', California','')
ACS5_final['median_age'] = ACS5_final['median_age'].astype(float)

In [10]:
def pct_to_numeric(pct_str):
    return float(pct_str.replace('%',''))

In [13]:
pct_cols = [cname for cname in ACS5_final.columns if cname.startswith('pct_')]

In [15]:
ACS5_final[pct_cols] = ACS5_final[pct_cols].map(pct_to_numeric)

In [18]:
ACS5_final

,county,median_age,pct_white,pct_black,pct_native,pct_asian,pct_other,pct_hispanic
0,Alameda County,38.7,41.8,12.1,2.1,36.1,19.1,23.3
1,Alpine County,41.1,71.0,0.0,28.1,0.5,8.3,14.7
2,Amador County,49.9,89.0,3.7,5.0,3.6,12.3,15.5
3,Butte County,36.3,84.3,3.1,4.3,7.1,13.6,19.5
4,Calaveras County,52.0,91.6,1.6,3.8,3.2,10.8,13.9
5,Colusa County,35.7,70.6,2.1,3.2,2.1,42.1,62.3
6,Contra Costa County,40.3,56.4,10.8,2.6,22.4,22.6,27.3
7,Del Norte County,40.8,78.1,3.9,10.3,4.8,14.0,19.6
8,El Dorado County,46.1,88.8,1.7,2.5,7.5,8.9,14.2
9,Fresno County,33.2,61.6,6.0,3.1,12.8,38.1,54.1
10,Glenn County,35.9,74.0,1.0,3.8,3.4,32.5,44.1
11,Humboldt County,39.6,85.2,3.2,8.6,5.2,10.6,13.8
12,Imperial County,33.0,55.6,3.7,2.7,2.3,62.7,85.6
13,Inyo County,45.6,78.3,1.3,15.1,2.8,15.5,23.8
14,Kern County,32.4,69.8,6.7,2.9,6.5,36.1,55.7
15,Kings County,32.3,65.5,7.9,3.1,5.1,38.7,57.5
16,Lake County,44.2,80.2,3.7,6.6,2.5,19.1,23.8
17,Lassen County,37.8,82.7,9.5,5.1,2.6,13.7,22.5
18,Los Angeles County,37.9,50.9,9.4,2.7,17.2,37.0,48.3
19,Madera County,34.6,61.3,4.1,5.0,3.5,45.5,60.4
20,Marin County,47.3,80.5,3.6,1.9,9.0,15.8,19.0
21,Mariposa County,51.6,89.1,2.4,6.2,2.5,11.0,13.7
22,Mendocino County,43.9,84.8,1.7,6.8,3.1,20.6,26.9
23,Merced County,31.8,46.9,4.4,3.0,8.8,49.5,62.7
24,Modoc County,49.0,89.6,1.5,6.3,1.5,10.0,15.3
25,Mono County,40.3,89.6,0.5,6.8,3.6,16.1,26.7
26,Monterey County,35.3,49.0,3.4,2.5,7.7,51.1,61.0
27,Napa County,42.8,73.2,3.4,2.5,10.5,24.8,35.9
28,Nevada County,50.3,94.5,1.2,2.6,3.5,7.7,10.5
29,Orange County,39.1,60.4,2.7,2.0,25.0,25.0,34.1
30,Placer County,42.4,84.0,3.2,2.4,12.2,11.1,15.4
31,Plumas County,52.1,94.7,3.1,4.9,1.1,3.9,10.0
32,Riverside County,36.7,59.5,8.4,3.1,9.1,39.1,50.6
33,Sacramento County,37.2,58.8,13.0,3.1,20.9,17.4,24.0
34,San Benito County,35.9,76.9,1.9,4.5,6.7,43.7,61.7
35,San Bernardino County,34.4,56.4,10.1,3.0,10.0,39.5,54.6
36,San Diego County,37.1,70.0,6.6,2.5,15.6,23.6,34.3
37,San Francisco County,39.7,50.1,6.8,1.8,39.1,13.1,15.9
38,San Joaquin County,35.2,55.1,9.1,6.1,21.1,30.5,42.2
39,San Luis Obispo County,40.2,86.8,2.5,2.6,5.9,17.5,24.5
40,San Mateo County,40.6,52.2,3.3,2.2,34.4,19.6,24.9
41,Santa Barbara County,34.5,76.8,2.9,3.6,7.4,33.0,47.6
42,Santa Clara County,37.9,45.5,3.6,1.9,42.7,19.7,25.1
43,Santa Cruz County,39.6,75.8,2.3,3.0,7.0,26.3,35.0
44,Shasta County,41.7,90.7,2.4,5.1,5.0,8.3,11.3
45,Sierra County,56.0,93.7,0.3,2.6,0.0,6.7,9.6
46,Siskiyou County,47.4,90.1,2.7,7.6,3.2,7.6,13.1
47,Solano County,39.1,55.1,16.4,2.8,20.4,19.5,29.0
48,Sonoma County,42.7,77.5,2.9,3.7,6.6,23.3,29.4
49,Stanislaus County,34.8,73.3,4.3,3.3,7.9,35.6,49.2
50,Sutter County,36.4,65.3,3.7,4.3,20.0,22.9,32.4
51,Tehama County,40.1,84.4,1.6,5.0,2.5,22.7,28.2
52,Trinity County,54.8,88.6,1.1,5.6,2.9,9.4,5.9
53,Tulare County,31.9,63.3,2.2,3.3,4.6,48.4,66.1
54,Tuolumne County,48.8,91.0,2.3,4.4,2.9,8.2,13.2
55,Ventura County,39.4,78.7,3.2,3.3,9.6,26.6,43.8
56,Yolo County,32.3,69.9,4.3,2.8,18.7,21.0,33.2
57,Yuba County,33.9,76.1,7.0,5.7,10.4,18.6,30.0
58,ZCTA5 99641,23.4,1.4,0.0,99.6,0.0,0.4,1.7

* Save cleaned and converted version back to `data` folder

In [19]:
ACS5_final.to_csv('../data/ACSDP05_final.csv', index=False)

## 2. ACSDP03 (socioeconomic data) (ACS data 3/3)

In [25]:
ACS3 = pd.read_csv('../data/ACSDP03.csv')

Selecting just the percent and estimate columns

In [26]:
estimate_cols = [c for c in ACS3.columns if c.endswith('!!Estimate')]
percent_cols = [c for c in ACS3.columns if c.endswith('!!Percent')]

Cleaning the county names

In [27]:
county_names = [c.split('!!')[0].strip() for c in percent_cols]

Constructing final dataset by locating desired measures and renaming columns

In [28]:
ACS3_final = pd.DataFrame({
    'county': county_names,

    'median_household_income': ACS3.loc[67, estimate_cols].values,
    'unemployment_rate': ACS3.loc[9, percent_cols].values,

    'pct_agriculture_mining': ACS3.loc[36, percent_cols].values,
    'pct_construction': ACS3.loc[37, percent_cols].values,
    'pct_manufacturing': ACS3.loc[38, percent_cols].values,
    'pct_wholesale_trade': ACS3.loc[39, percent_cols].values,
    'pct_retail_trade': ACS3.loc[40, percent_cols].values,
    'pct_transportation_warehousing_utilities': ACS3.loc[41, percent_cols].values,
    'pct_information': ACS3.loc[42, percent_cols].values,
    'pct_real_estate_rental_leasing': ACS3.loc[43, percent_cols].values,
    'pct_admin_waste_services': ACS3.loc[44, percent_cols].values,
    'pct_health_care_social_assistance': ACS3.loc[45, percent_cols].values,
    'pct_accommodation_food_services': ACS3.loc[46, percent_cols].values,
    'pct_other_services': ACS3.loc[47, percent_cols].values,
    'pct_public_administration': ACS3.loc[48, percent_cols].values,
})

In [32]:
ACS3_final

,county,median_household_income,unemployment_rate,pct_agriculture_mining,pct_construction,pct_manufacturing,pct_wholesale_trade,pct_retail_trade,pct_transportation_warehousing_utilities,pct_information,pct_real_estate_rental_leasing,pct_admin_waste_services,pct_health_care_social_assistance,pct_accommodation_food_services,pct_other_services,pct_public_administration
0,"Alameda County, California","122,488",4.9%,0.4%,5.3%,9.7%,2.1%,8.8%,5.5%,3.8%,6.0%,20.7%,21.8%,7.6%,4.5%,3.7%
1,"Alpine County, California","101,125",4.9%,9.0%,2.0%,5.7%,0.6%,19.7%,5.1%,0.8%,2.2%,10.1%,20.1%,21.2%,0.0%,3.6%
2,"Amador County, California","74,853",6.0%,4.4%,9.5%,5.3%,1.4%,10.1%,4.4%,1.4%,5.3%,10.8%,15.3%,12.6%,7.7%,11.6%
3,"Butte County, California","66,085",7.1%,3.7%,6.7%,6.4%,2.0%,12.0%,4.3%,2.1%,4.9%,10.7%,26.7%,11.8%,4.4%,4.4%
4,"Calaveras County, California","77,526",6.2%,3.4%,10.6%,5.5%,1.7%,11.2%,5.0%,1.7%,5.9%,11.9%,19.8%,8.6%,5.0%,9.7%
5,"Colusa County, California","69,619",7.4%,22.0%,4.7%,12.4%,2.2%,8.8%,7.8%,0.4%,1.7%,4.1%,15.8%,8.5%,4.6%,7.0%
6,"Contra Costa County, California","120,020",5.8%,0.6%,7.7%,6.2%,2.1%,10.1%,5.9%,2.5%,7.6%,17.2%,22.8%,8.2%,4.9%,4.3%
7,"Del Norte County, California","61,149",6.3%,5.2%,6.9%,4.6%,2.9%,12.0%,3.1%,0.8%,2.2%,6.6%,26.8%,11.2%,3.4%,14.4%
8,"El Dorado County, California","99,246",4.6%,1.6%,8.5%,6.2%,1.6%,9.6%,3.8%,1.7%,7.6%,14.0%,20.0%,13.1%,5.2%,7.1%
9,"Fresno County, California","67,756",8.6%,8.7%,6.3%,6.4%,3.2%,10.4%,6.4%,1.2%,4.3%,9.3%,24.9%,8.1%,4.7%,6.3%
10,"Glenn County, California","64,033",7.7%,16.8%,6.6%,10.2%,1.6%,13.0%,5.3%,0.1%,1.8%,5.1%,17.5%,8.0%,8.3%,5.6%
11,"Humboldt County, California","57,881",9.2%,5.1%,8.3%,4.5%,2.1%,13.2%,3.7%,1.2%,3.8%,9.6%,23.7%,11.7%,5.7%,7.4%
12,"Imperial County, California","53,847",13.2%,9.8%,6.2%,3.8%,2.9%,12.0%,6.7%,0.7%,3.2%,7.3%,23.2%,9.4%,4.1%,10.7%
13,"Inyo County, California","63,417",4.9%,1.5%,8.5%,3.5%,1.8%,7.2%,7.1%,2.1%,4.3%,6.5%,22.3%,14.7%,3.9%,16.5%
14,"Kern County, California","63,883",8.4%,14.2%,7.3%,5.4%,2.3%,10.6%,6.6%,0.9%,3.5%,8.3%,21.9%,8.2%,4.5%,6.4%
15,"Kings County, California","68,540",9.2%,15.6%,3.5%,8.8%,2.8%,10.3%,5.2%,0.8%,2.0%,6.5%,20.5%,8.2%,3.7%,11.9%
16,"Lake County, California","56,259",10.4%,5.9%,9.6%,5.2%,1.3%,12.6%,5.7%,1.2%,3.8%,10.0%,22.7%,8.8%,4.6%,8.7%
17,"Lassen County, California","59,515",7.9%,3.9%,6.9%,2.5%,1.6%,11.7%,5.8%,1.4%,1.5%,5.7%,18.5%,7.5%,3.2%,29.7%
18,"Los Angeles County, California","83,411",7.0%,0.5%,6.2%,8.7%,3.1%,10.0%,6.5%,4.4%,5.9%,13.5%,21.4%,10.7%,5.5%,3.6%
19,"Madera County, California","73,543",11.1%,14.2%,8.0%,9.1%,1.8%,9.2%,5.7%,1.2%,4.7%,7.2%,22.4%,6.8%,4.1%,5.5%
20,"Marin County, California","142,019",5.8%,1.0%,6.4%,4.7%,2.1%,9.9%,2.9%,4.0%,9.7%,20.9%,21.0%,8.4%,5.5%,3.5%
21,"Mariposa County, California","60,021",6.2%,4.4%,9.0%,3.2%,1.4%,9.2%,4.0%,0.6%,2.8%,6.8%,18.9%,20.5%,7.4%,12.0%
22,"Mendocino County, California","61,335",9.1%,6.8%,8.0%,6.9%,2.1%,13.5%,5.4%,0.8%,4.3%,8.4%,21.3%,11.0%,5.4%,6.2%
23,"Merced County, California","64,772",10.7%,11.4%,8.2%,10.8%,3.6%,10.9%,7.3%,0.9%,2.8%,6.5%,21.6%,7.5%,4.3%,4.3%
24,"Modoc County, California","54,962",7.6%,17.6%,4.8%,1.1%,1.4%,6.0%,5.6%,0.8%,1.9%,11.1%,22.1%,10.6%,6.7%,10.2%
25,"Mono County, California","82,038",1.9%,3.4%,7.3%,6.1%,0.0%,4.2%,3.1%,0.6%,11.9%,10.4%,15.2%,25.8%,6.5%,5.4%
26,"Monterey County, California","91,043",5.3%,14.7%,7.6%,5.6%,2.6%,9.4%,3.6%,1.3%,3.4%,10.5%,20.4%,11.1%,4.5%,5.3%
27,"Napa County, California","105,809",5.2%,5.4%,5.8%,13.1%,2.6%,10.2%,3.7%,1.3%,4.4%,10.7%,21.7%,12.7%,3.9%,4.2%
28,"Nevada County, California","79,395",4.4%,1.5%,9.4%,5.4%,1.4%,11.9%,4.6%,1.6%,5.2%,14.1%,23.1%,10.3%,6.9%,4.6%
29,"Orange County, California","109,361",5.4%,0.6%,6.0%,11.7%,3.2%,10.2%,4.1%,1.9%,8.7%,14.8%,20.5%,10.3%,5.0%,3.1%
30,"Placer County, California","109,375",4.3%,0.6%,7.5%,6.1%,2.1%,10.4%,4.6%,1.8%,8.6%,13.3%,23.2%,8.9%,4.4%,8.4%
31,"Plumas County, California","67,885",8.0%,7.7%,10.1%,7.8%,0.9%,7.5%,6.0%,0.9%,3.5%,7.0%,24.3%,10.7%,4.9%,8.8%
32,"Riverside County, California","84,505",6.7%,1.3%,9.5%,8.2%,2.7%,12.3%,7.5%,1.5%,5.0%,10.2%,20.8%,11.0%,4.9%,5.2%
33,"Sacramento County, California","84,010",6.3%,0.8%,7.1%,5.7%,2.3%,10.9%,6.4%,1.5%,6.3%,12.1%,21.6%,9.4%,5.0%,10.7%
34,"San Benito County, California","104,451",6.2%,6.4%,11.0%,11.0%,3.4%,10.3%,6.1%,1.3%,3.3%,10.4%,18.9%,9.4%,3.3%,5.2%
35,"San Bernardino County, California","77,423",7.2%,0.7%,8.1%,7.9%,3.2%,12.4%,11.7%,1.2%,4.3%,9.5%,21.4%,9.1%,5.0%,5.5%
36,"San Diego County, California","96,974",6.3%,0.7%,6.5%,9.8%,2.1%,10.2%,4.5%,2.0%,6.1%,16.3%,21.4%,10.6%,5.0%,4.9%
37,"San Francisco County, California","136,689",5.4%,0.2%,3.2%,5.0%,1.6%,8.4%,4.7%,6.2%,8.4%,26.4%,19.4%,9.0%,4.1%,3.4%
38,"San Joaquin County, California","82,837",7.2%,4.9%,8.8%,9.5%,2.7%,11.7%,9.0%,1.4%,4.5%,10.3%,20.0%,8.2%,4.3%,4.9%
39,"San Luis Obispo County, California","90,158",5.0%,3.5%,7.8%,8.0%,1.8%,10.8%,5.4%,1.8%,4.6%,11.7%,22.1%,11.9%,4.8%,5.8%
40,"San Mateo County, California","149,907",4.5%,0.6%,5.6%,7.5%,1.8%,8.7%,6.1%,4.9%,7.0%,21.2%,20.4%,8.3%,4.6%,3.3%
41,"Santa Barbara County, California","92,332",6.0%,8.3%,6.6%,7.2%,2.0%,9.5%,3.7%,1.9%,4.4%,12.9%,23.1%,11.2%,4.8%,4.4%
42,"Santa Clara County, California","153,792",4.4%,0.5%,5.1%,16.3%,1.7%,8.3%,3.1%,6.0%,4.4%,22.4%,19.1%,7.3%,3.5%,2.4%
43,"Santa Cruz County, California","104,409",5.9%,4.5%,7.1%,8.4%,2.2%,10.3%,4.2%,2.4%,4.3%,14.0%,24.3%,10.3%,4.4%,3.7%
44,"Shasta County, California","68,347",6.6%,2.1%,8.3%,5.1%,1.9%,12.1%,5.5%,1.2%,5.4%,10.2%,24.5%,10.3%,5.9%,7.7%
45,"Sierra County, California","61,108",5.6%,18.5%,13.7%,7.5%,0.0%,0.6%,5.6%,0.0%,2.3%,3.9%,23.3%,17.0%,1.5%,6.1%
46,"Siskiyou County, California","53,898",7.4%,8.6%,6.4%,6.3%,1.6%,11.5%,4.4%,2.1%,3.1%,6.8%,26.0%,10.5%,4.6%,8.1%
47,"Solano County, California","97,037",5.9%,1.3%,8.2%,8.6%,2.1%,11.4%,7.1%,1.8%,5.6%,11.0%,22.9%,8.3%,4.5%,7.3%
48,"Sonoma County, California","99,266",5.2%,2.4%,9.2%,10.3%,2.2%,11.3%,3.7%,1.8%,5.1%,12.3%,22.2%,9.8%,5.3%,4.4%
49,"Stanislaus County, California","74,872",8.2%,5.1%,8.9%,12.1%,3.0%,11.2%,7.7%,0.8%,3.5%,8.6%,21.4%,8.5%,4.8%,4.4%
50,"Sutter County, California","72,654",7.6%,9.3%,9.1%,6.8%,2.5%,12.9%,6.5%,0.9%,3.8%,8.1%,21.5%,8.6%,4.3%,5.7%
51,"Tehama County, California","59,029",7.4%,9.8%,7.3%,9.5%,1.1%,11.7%,7.2%,0.5%,3.1%,6.8%,22.9%,7.8%,3.9%,8.5%
52,"Trinity County, California","47,317",7.4%,12.6%,15.2%,3.9%,1.2%,11.9%,3.5%,1.7%,2.6%,4.9%,15.7%,15.4%,3.5%,8.1%
53,"Tulare County, California","64,474",9.0%,15.0%,6.6%,8.3%,2.9%,10.2%,5.2%,0.9%,2.9%,7.1%,22.2%,8.2%,4.3%,6.2%
54,"Tuolumne County, California","70,432",8.3%,2.4%,7.9%,5.4%,1.0%,8.8%,5.8%,1.3%,3.9%,10.1%,25.1%,14.6%,5.5%,8.1%
55,"Ventura County, California","102,141",5.3%,5.0%,6.2%,9.9%,2.9%,10.3%,3.8%,2.5%,6.7%,12.8%,20.1%,9.4%,4.9%,5.4%
56,"Yolo County, California","85,097",5.3%,3.9%,5.8%,6.1%,1.8%,9.1%,5.3%,1.1%,4.0%,11.9%,28.5%,10.1%,3.8%,8.5%
57,"Yuba County, California","66,693",7.4%,4.4%,8.7%,6.8%,2.1%,11.9%,5.8%,1.5%,4.3%,9.5%,22.1%,9.4%,4.8%,8.7%

## 3. ACSDP02 (educational attainment data) (ACS data 3/3)

In [33]:
ACS2 = pd.read_csv('../data/ACSDP02.csv')

Selecting just the percent column

In [12]:
percent_cols = [c for c in ACS2.columns if c.endswith('!!Percent')]

Cleaning the county names

In [13]:
county_names = [c.split('!!')[0].strip() for c in percent_cols]

Constructing final dataset by locating desired measure and renaming column

In [14]:
ACS2_final = pd.DataFrame({
    'county': county_names,
    'pct_bachelors_degree': ACS2.loc[75, percent_cols].values
})

Merging all three cleaned ACS datasets

In [15]:
final_df = (
    ACS5_final
    .merge(ACS3_final, on='county', how='left')
    .merge(ACS2_final, on='county', how='left')
)

Note: I encountered significant difficulty in my attempts to reshape the data (specifically, ensuring that the correct values were aligned with the right measures for each county after reshaping) so I relied heavily on ChatGPT to clean/reshape the data.