### ACS Data Analysis

Set up

In [1]:
import pandas as pd
import geopandas as gpd
import numpy as np
import camelot
import calendar
import re
import matplotlib.pyplot as plt

Loading in ACSDP05 (demographic data) (ACS data 1/3)

In [2]:
ACS5 = pd.read_csv('data/ACSDP05.csv')

To do
-Drop MoE columns
-Drop Estimate columns
-Rows to keep:
    -Median age
    -Race
        -
73	        Black or African American
74	        American Indian and Alaska Native
75	        Asian
76	        Native Hawaiian and Other Pacific Islander
77	        Some Other Race
	﻿"Label (Grouping)"
80	        Hispanic or Latino (of any race)
-Make county the rows

In [7]:
estimate_cols = [c for c in ACS5.columns if c.endswith('!!Estimate')]
percent_cols = [c for c in ACS5.columns if c.endswith('!!Percent')]

county_names = [c.split('!!')[0].strip() for c in percent_cols]

median_idx = ACS5['Label (Grouping)'].astype(str).str.contains('Median age', na=False)

ACS5_final = pd.DataFrame({
    'county': county_names,
    'median_age': ACS5.loc[median_idx, estimate_cols].iloc[0].values,
    'pct_white': ACS5.loc[71, percent_cols].values,
    'pct_black': ACS5.loc[72, percent_cols].values,
    'pct_native': ACS5.loc[73, percent_cols].values,
    'pct_asian': ACS5.loc[74, percent_cols].values,
    'pct_other': ACS5.loc[76, percent_cols].values,
    'pct_hispanic': ACS5.loc[79, percent_cols].values,
})

In [9]:
ACS5_final.head()

,county,median_age,pct_white,pct_black,pct_native,pct_asian,pct_other,pct_hispanic
0,"Alameda County, California",38.7,41.8%,12.1%,2.1%,36.1%,19.1%,23.3%
1,"Alpine County, California",41.1,71.0%,0.0%,28.1%,0.5%,8.3%,14.7%
2,"Amador County, California",49.9,89.0%,3.7%,5.0%,3.6%,12.3%,15.5%
3,"Butte County, California",36.3,84.3%,3.1%,4.3%,7.1%,13.6%,19.5%
4,"Calaveras County, California",52.0,91.6%,1.6%,3.8%,3.2%,10.8%,13.9%

In [13]:
ACS5.loc[71:80, ['Label (Grouping)', 'Amador County, California!!Estimate', 'Amador County, California!!Percent']]

,Label (Grouping),"Amador County, California!!Estimate","Amador County, California!!Percent"
71,White,"36,513",89.0%
72,Black or African American,"1,506",3.7%
73,American Indian and Alaska Native,"2,032",5.0%
74,Asian,"1,483",3.6%
75,Native Hawaiian and Other Pacific Isla...,226,0.6%
76,Some Other Race,"5,040",12.3%
77,HISPANIC OR LATINO AND RACE,NaN,NaN
78,Total population,"41,029","41,029"
79,Hispanic or Latino (of any race),"6,361",15.5%
80,Mexican,"4,244",10.3%

In [14]:
ACS3 = pd.read_csv('data/ACSDP03.csv')

In [16]:
estimate_cols = [c for c in ACS3.columns if c.endswith('!!Estimate')]
percent_cols = [c for c in ACS3.columns if c.endswith('!!Percent')]

county_names = [c.split('!!')[0].strip() for c in percent_cols]

ACS3_final = pd.DataFrame({
    'county': county_names,

    'median_household_income': ACS3.loc[67, estimate_cols].values,
    'unemployment_rate': ACS3.loc[9, percent_cols].values,

    'pct_agriculture_mining': ACS3.loc[36, percent_cols].values,
    'pct_construction': ACS3.loc[37, percent_cols].values,
    'pct_manufacturing': ACS3.loc[38, percent_cols].values,
    'pct_wholesale_trade': ACS3.loc[39, percent_cols].values,
    'pct_retail_trade': ACS3.loc[40, percent_cols].values,
    'pct_transportation_warehousing_utilities': ACS3.loc[41, percent_cols].values,
    'pct_information': ACS3.loc[42, percent_cols].values,
    'pct_real_estate_rental_leasing': ACS3.loc[43, percent_cols].values,
    'pct_admin_waste_services': ACS3.loc[44, percent_cols].values,
    'pct_health_care_social_assistance': ACS3.loc[45, percent_cols].values,
    'pct_accommodation_food_services': ACS3.loc[46, percent_cols].values,
    'pct_other_services': ACS3.loc[47, percent_cols].values,
    'pct_public_administration': ACS3.loc[48, percent_cols].values,
})

ACS3_final.head()

,county,median_household_income,unemployment_rate,pct_agriculture_mining,pct_construction,pct_manufacturing,pct_wholesale_trade,pct_retail_trade,pct_transportation_warehousing_utilities,pct_information,pct_real_estate_rental_leasing,pct_admin_waste_services,pct_health_care_social_assistance,pct_accommodation_food_services,pct_other_services,pct_public_administration
0,"Alameda County, California","122,488",4.9%,0.4%,5.3%,9.7%,2.1%,8.8%,5.5%,3.8%,6.0%,20.7%,21.8%,7.6%,4.5%,3.7%
1,"Alpine County, California","101,125",4.9%,9.0%,2.0%,5.7%,0.6%,19.7%,5.1%,0.8%,2.2%,10.1%,20.1%,21.2%,0.0%,3.6%
2,"Amador County, California","74,853",6.0%,4.4%,9.5%,5.3%,1.4%,10.1%,4.4%,1.4%,5.3%,10.8%,15.3%,12.6%,7.7%,11.6%
3,"Butte County, California","66,085",7.1%,3.7%,6.7%,6.4%,2.0%,12.0%,4.3%,2.1%,4.9%,10.7%,26.7%,11.8%,4.4%,4.4%
4,"Calaveras County, California","77,526",6.2%,3.4%,10.6%,5.5%,1.7%,11.2%,5.0%,1.7%,5.9%,11.9%,19.8%,8.6%,5.0%,9.7%

To do:

-Drop estimate, MoE, Percent MoE columns
-Keep all industry rows
-Keep Median household income (dollars)

In [17]:
ACS2 = pd.read_csv('data/ACSDP02.csv')

In [20]:
# percent columns
percent_cols = [c for c in ACS2.columns if c.endswith('!!Percent')]

# county names
county_names = [c.split('!!')[0].strip() for c in percent_cols]

# build dataset
ACS2_final = pd.DataFrame({
    'county': county_names,
    'pct_bachelors_degree': ACS2.loc[75, percent_cols].values
})

ACS2_final.head()

                            county pct_bachelors_degree
0       Alameda County, California                53.4%
1         Butte County, California                31.2%
2  Contra Costa County, California                46.2%
3     El Dorado County, California                42.4%
4        Fresno County, California                24.7%

To do:
-Drop estimate, MoE, Percent MoE columns
-Keep bachelor's degree or higher

In [38]:
final_df = (
    ACS5_final
    .merge(ACS3_final, on='county', how='left')
    .merge(ACS2_final, on='county', how='left')
)

In [39]:
print(final_df)

                    county median_age pct_white pct_black pct_native  \
0           Alameda County       38.7     41.8%     12.1%       2.1%
1            Alpine County       41.1     71.0%      0.0%      28.1%
2            Amador County       49.9     89.0%      3.7%       5.0%
3             Butte County       36.3     84.3%      3.1%       4.3%
4         Calaveras County       52.0     91.6%      1.6%       3.8%
5            Colusa County       35.7     70.6%      2.1%       3.2%
6      Contra Costa County       40.3     56.4%     10.8%       2.6%
7         Del Norte County       40.8     78.1%      3.9%      10.3%
8         El Dorado County       46.1     88.8%      1.7%       2.5%
9            Fresno County       33.2     61.6%      6.0%       3.1%
10            Glenn County       35.9     74.0%      1.0%       3.8%
11         Humboldt County       39.6     85.2%      3.2%       8.6%
12         Imperial County       33.0     55.6%      3.7%       2.7%
13             Inyo County       45.6     78.3%      1.3%      15.1%
14             Kern County       32.4     69.8%      6.7%       2.9%
15            Kings County       32.3     65.5%      7.9%       3.1%
16             Lake County       44.2     80.2%      3.7%       6.6%
17           Lassen County       37.8     82.7%      9.5%       5.1%
18      Los Angeles County       37.9     50.9%      9.4%       2.7%
19           Madera County       34.6     61.3%      4.1%       5.0%
20            Marin County       47.3     80.5%      3.6%       1.9%
21         Mariposa County       51.6     89.1%      2.4%       6.2%
22        Mendocino County       43.9     84.8%      1.7%       6.8%
23           Merced County       31.8     46.9%      4.4%       3.0%
24            Modoc County       49.0     89.6%      1.5%       6.3%
25             Mono County       40.3     89.6%      0.5%       6.8%
26         Monterey County       35.3     49.0%      3.4%       2.5%
27             Napa County       42.8     73.2%      3.4%       2.5%
28           Nevada County       50.3     94.5%      1.2%       2.6%
29           Orange County       39.1     60.4%      2.7%       2.0%
30           Placer County       42.4     84.0%      3.2%       2.4%
31           Plumas County       52.1     94.7%      3.1%       4.9%
32        Riverside County       36.7     59.5%      8.4%       3.1%
33       Sacramento County       37.2     58.8%     13.0%       3.1%
34       San Benito County       35.9     76.9%      1.9%       4.5%
35   San Bernardino County       34.4     56.4%     10.1%       3.0%
36        San Diego County       37.1     70.0%      6.6%       2.5%
37    San Francisco County       39.7     50.1%      6.8%       1.8%
38      San Joaquin County       35.2     55.1%      9.1%       6.1%
39  San Luis Obispo County       40.2     86.8%      2.5%       2.6%
40        San Mateo County       40.6     52.2%      3.3%       2.2%
41    Santa Barbara County       34.5     76.8%      2.9%       3.6%
42      Santa Clara County       37.9     45.5%      3.6%       1.9%
43       Santa Cruz County       39.6     75.8%      2.3%       3.0%
44           Shasta County       41.7     90.7%      2.4%       5.1%
45           Sierra County       56.0     93.7%      0.3%       2.6%
46         Siskiyou County       47.4     90.1%      2.7%       7.6%
47           Solano County       39.1     55.1%     16.4%       2.8%
48           Sonoma County       42.7     77.5%      2.9%       3.7%
49       Stanislaus County       34.8     73.3%      4.3%       3.3%
50           Sutter County       36.4     65.3%      3.7%       4.3%
51           Tehama County       40.1     84.4%      1.6%       5.0%
52          Trinity County       54.8     88.6%      1.1%       5.6%
53           Tulare County       31.9     63.3%      2.2%       3.3%
54         Tuolumne County       48.8     91.0%      2.3%       4.4%
55          Ventura County       39.4     78.7%      3.2%       3.3%
56             Yolo County       32.3     69.9%      4.3%       2.8%
57             Yuba County       33.9     76.1%      7.0%       5.7%

   pct_asian pct_other pct_hispanic median_household_income unemployment_rate  \
0      36.1%     19.1%        23.3%                 122,488              4.9%
1       0.5%      8.3%        14.7%                 101,125              4.9%
2       3.6%     12.3%        15.5%                  74,853              6.0%
3       7.1%     13.6%        19.5%                  66,085              7.1%
4       3.2%     10.8%        13.9%                  77,526              6.2%
5       2.1%     42.1%        62.3%                  69,619              7.4%
6      22.4%     22.6%        27.3%                 120,020              5.8%
7       4.8%     14.0%        19.6%                  61,149              6.3%
8       7.5%      8.9%        14.2%                  99,246              4.6%
9      12.8%     38.1%        54.1%                  67,756              8.6%
10      3.4%     32.5%        44.1%                  64,033              7.7%
11      5.2%     10.6%        13.8%                  57,881              9.2%
12      2.3%     62.7%        85.6%                  53,847             13.2%
13      2.8%     15.5%        23.8%                  63,417              4.9%
14      6.5%     36.1%        55.7%                  63,883              8.4%
15      5.1%     38.7%        57.5%                  68,540              9.2%
16      2.5%     19.1%        23.8%                  56,259             10.4%
17      2.6%     13.7%        22.5%                  59,515              7.9%
18     17.2%     37.0%        48.3%                  83,411              7.0%
19      3.5%     45.5%        60.4%                  73,543             11.1%
20      9.0%     15.8%        19.0%                 142,019              5.8%
21      2.5%     11.0%        13.7%                  60,021              6.2%
22      3.1%     20.6%        26.9%                  61,335              9.1%
23      8.8%     49.5%        62.7%                  64,772             10.7%
24      1.5%     10.0%        15.3%                  54,962              7.6%
25      3.6%     16.1%        26.7%                  82,038              1.9%
26      7.7%     51.1%        61.0%                  91,043              5.3%
27     10.5%     24.8%        35.9%                 105,809              5.2%
28      3.5%      7.7%        10.5%                  79,395              4.4%
29     25.0%     25.0%        34.1%                 109,361              5.4%
30     12.2%     11.1%        15.4%                 109,375              4.3%
31      1.1%      3.9%        10.0%                  67,885              8.0%
32      9.1%     39.1%        50.6%                  84,505              6.7%
33     20.9%     17.4%        24.0%                  84,010              6.3%
34      6.7%     43.7%        61.7%                 104,451              6.2%
35     10.0%     39.5%        54.6%                  77,423              7.2%
36     15.6%     23.6%        34.3%                  96,974              6.3%
37     39.1%     13.1%        15.9%                 136,689              5.4%
38     21.1%     30.5%        42.2%                  82,837              7.2%
39      5.9%     17.5%        24.5%                  90,158              5.0%
40     34.4%     19.6%        24.9%                 149,907              4.5%
41      7.4%     33.0%        47.6%                  92,332              6.0%
42     42.7%     19.7%        25.1%                 153,792              4.4%
43      7.0%     26.3%        35.0%                 104,409              5.9%
44      5.0%      8.3%        11.3%                  68,347              6.6%
45      0.0%      6.7%         9.6%                  61,108              5.6%
46      3.2%      7.6%        13.1%                  53,898              7.4%
47     20.4%     19.5%        29.0%                  97,037              5.9%
48      6.6%     23.3%        29.4%                  99,266              5.2%
49      7.9%     35.6%        49.2%                  74,872              8.2%
50     20.0%     22.9%        32.4%                  72,654              7.6%
51      2.5%     22.7%        28.2%                  59,029              7.4%
52      2.9%      9.4%         5.9%                  47,317              7.4%
53      4.6%     48.4%        66.1%                  64,474              9.0%
54      2.9%      8.2%        13.2%                  70,432              8.3%
55      9.6%     26.6%        43.8%                 102,141              5.3%
56     18.7%     21.0%        33.2%                  85,097              5.3%
57     10.4%     18.6%        30.0%                  66,693              7.4%

    ... pct_retail_trade pct_transportation_warehousing_utilities  \
0   ...             8.8%                                     5.5%
1   ...            19.7%                                     5.1%
2   ...            10.1%                                     4.4%
3   ...            12.0%                                     4.3%
4   ...            11.2%                                     5.0%
5   ...             8.8%                                     7.8%
6   ...            10.1%                                     5.9%
7   ...            12.0%                                     3.1%
8   ...             9.6%                                     3.8%
9   ...            10.4%                                     6.4%
10  ...            13.0%                                     5.3%
11  ...            13.2%                                     3.7%
12  ...            12.0%                                     6.7%
13  ...             7.2%                                     7.1%
14  ...            10.6%                                     6.6%
15  ...            10.3%                                     5.2%
16  ...            12.6%                                     5.7%
17  ...            11.7%                                     5.8%
18  ...            10.0%                                     6.5%
19  ...             9.2%                                     5.7%
20  ...             9.9%                                     2.9%
21  ...             9.2%                                     4.0%
22  ...            13.5%                                     5.4%
23  ...            10.9%                                     7.3%
24  ...             6.0%                                     5.6%
25  ...             4.2%                                     3.1%
26  ...             9.4%                                     3.6%
27  ...            10.2%                                     3.7%
28  ...            11.9%                                     4.6%
29  ...            10.2%                                     4.1%
30  ...            10.4%                                     4.6%
31  ...             7.5%                                     6.0%
32  ...            12.3%                                     7.5%
33  ...            10.9%                                     6.4%
34  ...            10.3%                                     6.1%
35  ...            12.4%                                    11.7%
36  ...            10.2%                                     4.5%
37  ...             8.4%                                     4.7%
38  ...            11.7%                                     9.0%
39  ...            10.8%                                     5.4%
40  ...             8.7%                                     6.1%
41  ...             9.5%                                     3.7%
42  ...             8.3%                                     3.1%
43  ...            10.3%                                     4.2%
44  ...            12.1%                                     5.5%
45  ...             0.6%                                     5.6%
46  ...            11.5%                                     4.4%
47  ...            11.4%                                     7.1%
48  ...            11.3%                                     3.7%
49  ...            11.2%                                     7.7%
50  ...            12.9%                                     6.5%
51  ...            11.7%                                     7.2%
52  ...            11.9%                                     3.5%
53  ...            10.2%                                     5.2%
54  ...             8.8%                                     5.8%
55  ...            10.3%                                     3.8%
56  ...             9.1%                                     5.3%
57  ...            11.9%                                     5.8%

   pct_information pct_real_estate_rental_leasing pct_admin_waste_services  \
0             3.8%                           6.0%                    20.7%
1             0.8%                           2.2%                    10.1%
2             1.4%                           5.3%                    10.8%
3             2.1%                           4.9%                    10.7%
4             1.7%                           5.9%                    11.9%
5             0.4%                           1.7%                     4.1%
6             2.5%                           7.6%                    17.2%
7             0.8%                           2.2%                     6.6%
8             1.7%                           7.6%                    14.0%
9             1.2%                           4.3%                     9.3%
10            0.1%                           1.8%                     5.1%
11            1.2%                           3.8%                     9.6%
12            0.7%                           3.2%                     7.3%
13            2.1%                           4.3%                     6.5%
14            0.9%                           3.5%                     8.3%
15            0.8%                           2.0%                     6.5%
16            1.2%                           3.8%                    10.0%
17            1.4%                           1.5%                     5.7%
18            4.4%                           5.9%                    13.5%
19            1.2%                           4.7%                     7.2%
20            4.0%                           9.7%                    20.9%
21            0.6%                           2.8%                     6.8%
22            0.8%                           4.3%                     8.4%
23            0.9%                           2.8%                     6.5%
24            0.8%                           1.9%                    11.1%
25            0.6%                          11.9%                    10.4%
26            1.3%                           3.4%                    10.5%
27            1.3%                           4.4%                    10.7%
28            1.6%                           5.2%                    14.1%
29            1.9%                           8.7%                    14.8%
30            1.8%                           8.6%                    13.3%
31            0.9%                           3.5%                     7.0%
32            1.5%                           5.0%                    10.2%
33            1.5%                           6.3%                    12.1%
34            1.3%                           3.3%                    10.4%
35            1.2%                           4.3%                     9.5%
36            2.0%                           6.1%                    16.3%
37            6.2%                           8.4%                    26.4%
38            1.4%                           4.5%                    10.3%
39            1.8%                           4.6%                    11.7%
40            4.9%                           7.0%                    21.2%
41            1.9%                           4.4%                    12.9%
42            6.0%                           4.4%                    22.4%
43            2.4%                           4.3%                    14.0%
44            1.2%                           5.4%                    10.2%
45            0.0%                           2.3%                     3.9%
46            2.1%                           3.1%                     6.8%
47            1.8%                           5.6%                    11.0%
48            1.8%                           5.1%                    12.3%
49            0.8%                           3.5%                     8.6%
50            0.9%                           3.8%                     8.1%
51            0.5%                           3.1%                     6.8%
52            1.7%                           2.6%                     4.9%
53            0.9%                           2.9%                     7.1%
54            1.3%                           3.9%                    10.1%
55            2.5%                           6.7%                    12.8%
56            1.1%                           4.0%                    11.9%
57            1.5%                           4.3%                     9.5%

   pct_health_care_social_assistance pct_accommodation_food_services  \
0                              21.8%                            7.6%
1                              20.1%                           21.2%
2                              15.3%                           12.6%
3                              26.7%                           11.8%
4                              19.8%                            8.6%
5                              15.8%                            8.5%
6                              22.8%                            8.2%
7                              26.8%                           11.2%
8                              20.0%                           13.1%
9                              24.9%                            8.1%
10                             17.5%                            8.0%
11                             23.7%                           11.7%
12                             23.2%                            9.4%
13                             22.3%                           14.7%
14                             21.9%                            8.2%
15                             20.5%                            8.2%
16                             22.7%                            8.8%
17                             18.5%                            7.5%
18                             21.4%                           10.7%
19                             22.4%                            6.8%
20                             21.0%                            8.4%
21                             18.9%                           20.5%
22                             21.3%                           11.0%
23                             21.6%                            7.5%
24                             22.1%                           10.6%
25                             15.2%                           25.8%
26                             20.4%                           11.1%
27                             21.7%                           12.7%
28                             23.1%                           10.3%
29                             20.5%                           10.3%
30                             23.2%                            8.9%
31                             24.3%                           10.7%
32                             20.8%                           11.0%
33                             21.6%                            9.4%
34                             18.9%                            9.4%
35                             21.4%                            9.1%
36                             21.4%                           10.6%
37                             19.4%                            9.0%
38                             20.0%                            8.2%
39                             22.1%                           11.9%
40                             20.4%                            8.3%
41                             23.1%                           11.2%